language: python
python: "2.6"
install:
    - "pip install jinja2"
    - "pip install mock"
    - "pip install coverage"
    - "pip install coveralls --use-mirrors"
before_script:
    - "touch /tmp/test"
script:
    - "python setup.py install && nosetests --with-coverage --cover-package=soy"
    - "coverage run --source=soy, python setup.py install"
    - "coverage report -m"
after_success: "coveralls"
