language: python
python: "2.6"
install:
    - "pip install jinja2"
    - "pip install mock"
    - "pip install coverage"
before_script:
    - "touch /tmp/test"
script: "python setup.py install && nosetests --with-coverage"
