language: python
python: "2.6"
install:
    - "pip install jinja2"
    - "pip install mock"
    - "pip install coverage"
    - "pip install coveralls --use-mirrors"
before_script:
    - "touch /tmp/test"
script:
    - "python setup.py install && nosetests --doctest-extension=tests --cov=soy --cov-report=term --with-coverage --cover-package=soy"
    - "coverage run --source=soy,soy/tests setup.py install"
    - "coverage report"
after_success: "coveralls"
