language: python
python: "2.6"
install:
    - "pip install jinja2"
    - "pip install mock"
    - "pip install coverage"
    - "pip install coveralls --use-mirrors"
    - "pip install nose-cov"
before_script:
    - "touch /tmp/test"
script: "python setup.py install && nosetests --with-coverage --cov-config .coveragerc --cover-package=soy"
after_success: "coveralls"
